### ISSUE TITLE
Support separation of frontend and backend architecture

### ISSUE THREAD

**Issue by deanzd** [Azure/azure-spring-initializr#20]
We usually use separation of frontend and backend architecture or abbreviated as `separation`. 
The technologies we used are as below:

front-end:  Vue + Ant Design Vue
back-end: Java + Springboot

According to the corresponding architecture, generate the project.

**Comment by deanzd** [comment]
[Separation Architecture.zip](https://github.com/Azure/azure-spring-initializr/files/8579002/Separation.Architecture.zip)

You can reference the architecture of this demo

**Comment by deanzd** [comment]
[frontend-backend-jar.zip](https://github.com/Azure/azure-spring-initializr/files/8841801/frontend-backend-jar.zip)

**Comment by stliu** [comment]
drop from plan
