### ISSUE TITLE
Generate default github actions in generated project

### ISSUE THREAD

**Issue by stliu** [Azure/azure-spring-initializr#24]
## Context
Spring initializr generates `.gitignore` by default.

## Goal
We should also generate a github action file based on the :

1. JDK version
2. Language
3. Build system

**Comment by stliu** [comment]
@backwind1233 could you give it a try?

**Comment by stliu** [comment]
you can reference these:

* `io.spring.initializr.generator.spring.configuration.ApplicationPropertiesContributor`
* `io.spring.initializr.generator.spring.scm.git.GitIgnoreContributor`
* https://github.com/Azure/azure-spring-initializr/blob/main/.github/workflows/maven.yml

**Comment by fangjian0423** [comment]
Close it because the [My Azure Initializr project](https://github.com/fangjian0423/azure-spring-initializr) finishes.

If the code needs review and merge to this repository in the future, will reopen the issue.
