### ISSUE TITLE
Enbale tracking and collecting the data usage of Azure Spring Initializr project generation

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-spring-initializr#53]
### Context
Collect the number of generated projects, the metadata of generated projects (JDK version, Spring versions, Spring Cloud Azure versions), and the success rates of generating projects. 

What's the problem to solve?
- Filter the project generation request log to Log Analysis
- Parse the JSON format log to Kusto for the BI report
- Reduce dependencies on additional resources or tools

Candidate solutions for ETL:
The log in Azure Spring Cloud can be sent to the following destinations
- ❌**Log Analysis (ASC service level)**
  The JSON format log can not be directly passed to the structured log into a Kusto table, then the data should be exported into Storage Account first, then Kusto does ingestion from the Storage Account.

- **Storage Account**
 2 subs solutions when using Storage Account:
   - ❌**Send log to Storage Account in ASC service level**
     The same question to solve is to parse the JSON log format before ingestion of the data into Kusto.
  
   - ❌**Send log into Storage directly in the application of the ASC**
     This solution can solve the JSON data parsing, but another question is to control the right size to upload the blob to trigger the blob-created event which the Kusto will listen to the event in a special container, and lots of log data will be merged first, then move to the special container. The blob files of the subfolder will not be listened to transform data, this will bring the additional process to do the data moving.
     Also, the blob files should regularly be maintained.

- **Event Hubs**
 2 subs solutions when using Event Hub:
   - ❌**Send log to Event Hub in ASC service level**
     The same question to solve is to parse the JSON log format before Kusto consumes the event for ingestion.
  
   - ✅**Send log into Event Hub directly in the application of the ASC**
     This solution can solve the JSON data parsing, and the data in Kusto does not need to change anymore.

### Goal
- Collect the data of the project generation which contains the success and failure request
- Daily and monthly generated project number report
  - Can filter by JDK version, Spring Boot versions, language

### Solutions
- Output project generation logs to 2 EventHubs when enabling the EventHub stats
- Kusto will ingest the log via consuming the structured data from a special Event Hub
- Generate BI report from the Kutso data.

**Comment by stliu** [comment]
I think we should also collect where the request come from, like from a browser, which host; or from cmd line, or from whatever tool?

**Comment by stliu** [comment]
drop from plan
