### ISSUE TITLE
Support pushing the generated project to Github

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-spring-initializr#54]
**Context**
[Azure Spring Initializr](https://aka.ms/spring/start) is a project based on [start.spring.io](https://github.com/spring-io/start.spring.io ) , it can generate projects with selected options, the generated projects can be downloaded in zip format or be previewed online.

**Goal**
Support to push the generated projects into github repository directly.

**Comment by stliu** [comment]
done by @fangjian0423
