### ISSUE TITLE
[FEATURE REQ]Improve README documentation in azure-spring-initializr

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-spring-initializr#65]
**Is your feature request related to a problem? Please describe.**
The current [README.md](https://github.com/Azure/azure-spring-initializr/blob/main/README.md) documentation is very simple and has a lot can be improved.
It can include sections like 
- How to Build
- How to Run Locally
- Contributors
- etc

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by stliu** [comment]
drop from plan, closing it
