### ISSUE TITLE
[FEATURE REQ]Azure Spring Initializr: Support run on cloud

### ISSUE THREAD

**Issue by fangjian0423** [Azure/azure-spring-initializr#87]
Add a "run on cloud" button in README on the generated project.

Action: Login Azure and generate credential information, and store the credential to `secrets.AZURE_CREDENTIALS` on repository action secrets.

**Comment by chenrujun** [comment]
FYI: This project can be used to create `AZURE_CREDENTIAL` and push to GitHub by on-click. 
https://github.com/chenrujun/create-azure-credential-and-push-to-github-actions-secrets

**Comment by chenrujun** [comment]
Assign this issue to @fangjian0423  because I finished my part:  Creating `AZURE_CREDENTIAL` and push to GitHub by on-click.

**Comment by fangjian0423** [comment]
[AZD pipeline](https://dev.azure.com/azure-spring-integration/spring-integration-private/_wiki/wikis/spring-integration-private.wiki/361/Azure-Developer-CLI(AZD)-experience?anchor=azd-pipeline) provide similar feature.

**Comment by fangjian0423** [comment]
Close it because the feature has been done.
