### ISSUE TITLE
Integrate with IAM

### ISSUE THREAD

**Issue by deanzd** [Azure/azure-spring-initializr#9]
Add configuration to support SSO, you can choose use it or not.
1. Login by Oauth2
2. Record generation history
3. The admin can view this records

**Comment by stliu** [comment]
I don't understand this feature request

The spring initialize doesn't have a user system, nor required login to use

**Comment by stliu** [comment]
rethinking this, I think this is a valid requirement.

we may support such configuration:

`login.required=true` -- which is `false` by default.

when this is set to true, it is required to login before using this service.

And there is already a https://github.com/Azure/azure-spring-initializr/blob/main/initializr-extension/src/main/java/com/azure/spring/initializr/web/project/ProjectGenerationListener.java, currently it is just logging the project generation result ( success or fail ) to log, but it is easy to implement another listener to log the generation result to database, with current login user info, if the `login.required` property is enabled.

**Comment by stliu** [comment]
drop from plan
