### ISSUE TITLE
[FEATURE REQ]Azure Spring Initializr: Support AZD

### ISSUE THREAD

**Issue by fangjian0423** [Azure/azure-spring-initializr#90]
Generate files that support deploy to Azure by AZD.

File list:

- infra/ directory
- .azure.yaml
- github workflow for azd

We can refer this [todo-java-postgresql-terraform](https://github.com/fangjian0423/todo-java-postgresql-terraform) template.

**Comment by stliu** [comment]
just copy the files into generated project, no need to dynamic generated based on configuration

**Comment by fangjian0423** [comment]
Check it in [Azure Spring Initializr](https://spring-initializr-dev-spring-initializr-dev.azuremicroservices.io/).

Use bicep as infra provider and deploy to App Service.
